CREATE DATABASE IF NOT EXISTS meapi;
USE meapi;

CREATE TABLE profile (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100),
  email VARCHAR(100),
  education VARCHAR(255),
  work VARCHAR(255)
);

CREATE TABLE skills (
  id INT PRIMARY KEY AUTO_INCREMENT,
  profile_id INT,
  skill VARCHAR(50),
  FOREIGN KEY (profile_id) REFERENCES profile(id) ON DELETE CASCADE
);

CREATE TABLE links (
  id INT PRIMARY KEY AUTO_INCREMENT,
  profile_id INT,
  github VARCHAR(255),
  linkedin VARCHAR(255),
  FOREIGN KEY (profile_id) REFERENCES profile(id) ON DELETE CASCADE
);
